# Generated by Django 5.0.6 on 2024-06-10 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rename_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileRename',
            new_name='FileUpload',
        ),
    ]
