# Generated by Django 5.0.6 on 2024-06-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rename_app', '0002_rename_filerename_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='renamedZipFileURL',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
