# Generated by Django 5.0 on 2025-01-21 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rename_app', '0003_fileupload_renamedzipfileurl'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='imageNameDict',
            field=models.TextField(blank=True, null=True),
        ),
    ]
