# Generated by Django 5.0 on 2025-01-23 21:24

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rename_app', '0004_fileupload_imagenamedict'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='uKey',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, null=True, unique=True),
        ),
    ]
